# This workflow will check compliance to code style
# It will generate an html report

name: Checkstyle with Gradle

on:
  workflow_run:
    workflows:
      - Update Documentation
    types:
      - completed


jobs:
  checkstyle:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x Implementation/gradlew
    - name: Run checkstyle tasks
      run: cd Implementation && ./gradlew CheckstyleMain