# This workflow will update the documentation for the project

name: Update Documentation

on: workflow_dispatch


jobs:

  gendocs:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Execute documentation update script
      run: chmod +x update-docs.sh && ./update-docs.sh