# This workflow will update the documentation for the project

name: Update Documentation

on:
  pull_request:
    paths: 
      - 'Implementation/**'
      - '.github/workflows/**'
      - 'UML/**'
    branches: [ main ]


jobs:

  gendocs:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set up Graphviz environment
      uses: kamiazya/setup-graphviz@v1
    - name: Execute documentation update script
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: chmod +x update-docs.sh && ./update-docs.sh