# This workflow will update the documentation for the project

name: Update Documentation

on:
  push:
    paths: 
      - 'Implementation/**'
      - '.github/workflows/**'
      - 'UML/**'
    branches: [ main ]


jobs:

  gendocs:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        path: pixelboat
    
    - name: Checkout website repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        path: pixelboatWebsite
        repository: Frinksy/PixelBoatWebsite
  
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Set up Graphviz environment
      uses: kamiazya/setup-graphviz@v1

    - name: Execute Documentation Update Script
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: cd pixelboat && chmod +x update-docs.sh && ./update-docs.sh